### ISSUE TITLE
[coc.nvim] Error on activate extension coc-project: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by sainnhe** [iamcco/coc-project#16]
**Describe the bug**

After updating coc to latest version (I use `2d5e9a12` on master branch), an error message will be printed on startup:

```
[coc.nvim] Error on activate extension coc-project: Cannot read properties of undefined (reading 'then')
```

**To Reproduce**
1. Launch nvim: `$ nvim`
2. See error

**Expected behavior**
Launch without this error message.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:05 PST 2021; root:xnu-7195.141.14~1/RELEASE_ARM64_T8101`

Log:

```
## versions

vim version: NVIM v0.6.0
node version: v16.13.2
coc.nvim version: 0.0.80-2d5e9a12cb
coc.nvim directory: /Users/sainnhe/.local/share/nvim/plugins/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-01-24T10:22:01.986 INFO (pid:68844) [services] - registered service "diagnostic-languageserver"
2022-01-24T10:22:02.045 INFO (pid:68844) [coc-git] - Looking for git in: git
2022-01-24T10:22:02.056 INFO (pid:68844) [services] - registered service "highlight"
2022-01-24T10:22:02.060 WARN (pid:68844) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.activate (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-imselect/lib/index.js:78:43)
    at /Users/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:58363:37
2022-01-24T10:22:02.409 INFO (pid:68844) [plugin] - coc.nvim initialized with node: v16.13.2 after 510ms
2022-01-24T10:22:02.410 ERROR (pid:68844) [extensions] - Error on active extension coc-project: Cannot read properties of undefined (reading 'then') TypeError: Cannot read properties of undefined (reading 'then')
    at Object.<anonymous> (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:4765)
    at /Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:2754
    at Object.next (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:2859)
    at /Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:1771
    at new Promise (<anonymous>)
    at o (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:1545)
    at Object.t.activate (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-project/out/index.js:1:3072)
    at /Users/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:58363:37
    at new Promise (<anonymous>)
    at Object.activate (/Users/sainnhe/.local/share/nvim/plugins/coc.nvim/build/index.js:58361:22)
2022-01-24T10:22:02.431 INFO (pid:68844) [attach] - receive notification: highlight []
2022-01-24T10:22:02.433 INFO (pid:68844) [attach] - receive notification: runCommand [ 'explorer', '/Users/sainnhe/.local/share/nvim/plugins/coc.nvim' ]
2022-01-24T10:22:02.440 INFO (pid:68844) [coc-imselect] - Observer for input change started
2022-01-24T10:22:02.441 WARN (pid:68844) [workspace] - workspace.createStatusBarItem is deprecated, please use window.createStatusBarItem instead. 
    at Object.t.initStatusBar (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:155873)
    at Object.t.activate (/Users/sainnhe/.local/share/nvim/coc/extensions/node_modules/coc-spell-checker/out/index.js:1:23099)
2022-01-24T10:22:02.502 INFO (pid:68844) [attach] - receive notification: runCommand [ 'git.refresh' ]
2022-01-24T10:22:02.559 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 4 ]
2022-01-24T10:22:02.559 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 6 ]
2022-01-24T10:22:02.561 INFO (pid:68844) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_coc_helper_1',
  'BufDelete',
  5
]
2022-01-24T10:22:02.561 INFO (pid:68844) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_13_0_explorer_2',
  'BufDelete',
  5
]
2022-01-24T10:22:02.572 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 4 ]
2022-01-24T10:22:02.572 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 6 ]
2022-01-24T10:22:02.584 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 4 ]
2022-01-24T10:22:02.584 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 6 ]
2022-01-24T10:22:02.588 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 4 ]
2022-01-24T10:22:02.589 INFO (pid:68844) [attach] - receive notification: doAutocmd [ 6 ]
2022-01-24T10:22:04.182 INFO (pid:68844) [attach] - receive notification: showInfo []
```

**Comment by sainnhe** [comment]
Thanks! I can confirm that it has been fixed now.
